apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: abhiapp1
  name: abhiapp1
  namespace: abhi-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: abhiapp1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: abhiapp1
    spec:
      containers:
      - image: abhimobi007/testjenpush:appv1
        name: testjenpush
        ports:
        - containerPort: 80
        env:
        - name: deploy
          value: app1
        resources: {}
        imagePullPolicy: Always


# Adding service 
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: abhisvc1
  name: abhisvc1
  namespace: abhi-project
spec:
  ports:
  - name: 1432-80
    port: 1432
    protocol: TCP
    targetPort: 80
  selector:
    app: abhiapp1
  type: NodePort
status:
  loadBalancer: {}
